### ISSUE TITLE
Disable caching or getting live data

### ISSUE THREAD

**Issue by Speedy11CZ** [stelar7/R4J#19]
Hi. Because i want to connect summoner with discord using icon verification, i need live data. How to disable caching or request new icon?

**Comment by stelar7** [comment]
You can turn off the cache by doing `DataCall.setCacheProvider(null);`
You can also clear it for a endpoint by doing `DataCall.getCacheProvider().clear(URLEndpoint.WHATEVER_GOES_HERE, Collections.emptyMap())`
