### ISSUE TITLE
Can this API get info about what players are in queue and what champ did summoner picked? 

### ISSUE THREAD

**Issue by 1337-Sim** [stelar7/R4J#22]
Hey, I'm new to the dev side of LoL. I wanted to make a simple application that grabs the username of players in the lobby and the champ that the summoner picked.

**Comment by stelar7** [comment]
Hi. 

While it is possible to do what youre asking, im not 100% sure how.

I'd reccomend you join the riot games api discord and ask for help about how to do things in the #lcu-api channel.
https://discordapp.com/invite/riotgamesdevrel
