### ISSUE TITLE
class R4J getMatchV5API method is missing.

### ISSUE THREAD

**Issue by quittypig** [stelar7/R4J#25]
Only getMatchAPI() exists.
To use LOL Match V5 api, we need getMatchV5API in R4J class.

```
public MatchAPI getMatchAPI() {
    return MatchAPI.getInstance();
}
```

**Comment by domisum** [comment]
I already reported this, their answer:

`its not there, since its still in beta. use MatchV5API.getInstance() for now`

**Comment by quittypig** [comment]
Thanks~

**Comment by stelar7** [comment]
This is now added in v2.0.0 :)
