### ISSUE TITLE
Summoner not found with /lol/summoner/v4/summoners/by-name/ while existing

### ISSUE THREAD

**Issue by KaluNight** [stelar7/R4J#38]
Hello @stelar7 ! I hope everthing goes well on your side.

### I think I found two problems related to the endpoint /lol/summoner/v4/summoners/by-name/

**First problem:**
The nickname "Y K" in NA is impossible to find. But it really exists. OPGG: https://na.op.gg/summoners/na/Y%20K

The problem comes from Utils.normalizeString(args1). Just remove the data.replaceAll("\s+", "") should be enough to fix the issue. But I don't know if it had any use before that.

**Second problem:**
Can't find the nickname "夜" in NA as well. It is also found on OPGG (https://na.op.gg/summoners/na/%E5%A4%9C) but impossible to find it using the Riot api (with R4J and by hand) this time.

I don't know where the problem could come from, maybe you have an idea?

Thank you for your help !

**Comment by stelar7** [comment]
First problem is fixed in 2.1.7
Ive contacted Riot about issue number two, and will update you if i get a response.
