### ISSUE TITLE
Serialize raw json

### ISSUE THREAD

**Issue by mastrayer** [stelar7/R4J#41]
hi @stelar7

I have two service and use another library for using riot api each service.
But when i serialize LOLMatch and LOLTimeline, it's not like Riot API Response.
I'm using json serialize library Jackson, How can i serialize class to same API response?

Especially, Enum (ex. TeamType, SpellSlotType, GameModeType, ...) had lots problem. 
I tried to override serializer/deserializer for each enum, but there are too many enums and some enums are irreversible (ex. SpellSlotType).

Thanks.

**Comment by stelar7** [comment]
There is no way to serialize some classes back to its api values (mainly due to destructive transformations for enums)

If you need the raw json of those classes, you can use the MatchBuilder class, and call `getMatchRaw()`.
