### ISSUE TITLE
Toggle cache/specify location

### ISSUE THREAD

**Issue by AjaxIsLemons** [stelar7/R4J#44]
trying to reuse this library in a lambda function, which only gives write permission to /tmp directory. Would be nice to be able to toggle the disk cache or only use memory

**Comment by stelar7** [comment]
You can turn off cache / change the provider.
See this test fir examples
https://github.com/stelar7/R4J/blob/master/src/test/java/no/stelar7/api/r4j/tests/cache/CacheTest.java

Do note that only the filesystem cache is working 100%
