### ISSUE TITLE
NullPointerException at LOLMatch#gameEndTimestamp

### ISSUE THREAD

**Issue by NichtFilip** [stelar7/R4J#48]
Hello, while coding with your (really wonderful) library i encounted the following problem:

> Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "this.gameEndTimestamp" is null
> 	at no.stelar7.api.r4j.pojo.lol.match.v5.LOLMatch.getGameEndTimestamp(LOLMatch.java:99) ~[R4J-2.1.18.jar:na]

The error is caused by the method LOLMatch#getGameEndTimestamp if you try to get match data from matches prior to patch 11.20.

The gameEndTimestamp is 'Long' while the return-type being 'long'. This gets converted by the method 'Long.longValue()' and if gameEndTimestamp is null it throws this NullPointerException. 

GameEndTimestamp can be null because matches prior to patch 11.20 don't have this field.

**Comment by stelar7** [comment]
Fixed in 2.1.19
