### ISSUE TITLE
StaticLoRCard name error in region variable and regionRef

### ISSUE THREAD

**Issue by Anonymize** [stelar7/R4J#49]
### Problem

Version 2.1.19

The function **loadCards** in the class **LoRStaticAPI** is loading all _regions_ and _regionRefs_ null.

### Description

The library is calling and parsing data of cards from static api and loading to a list of  **StaticLoRCard** but the name of key in the Json file and variable in **StaticLoRCard** is different. 
Need change the name of variables in  **StaticLoRCard** from region to regions, and regionRef to regionRefs and the two now are lists.

![imagen](https://user-images.githubusercontent.com/9299990/178135655-f0da1044-c5f2-4b29-90e9-37ad5e1720b0.png)
![imagen](https://user-images.githubusercontent.com/9299990/178135679-df5b2080-c40b-42ca-9665-24e39b098692.png)

**Comment by stelar7** [comment]
Fixed in 2.1.20

**Comment by Anonymize** [comment]
Thanks for fixing it. But there is a missing class to update (LoRStaticAPI) to reference the new function in the lambda.

`[ERROR] /home/jitpack/build/src/main/java/no/stelar7/api/r4j/impl/lor/LoRStaticAPI.java:[82,31] cannot find symbol
  symbol:   method getRegionRef()
  location: variable c of type no.stelar7.api.r4j.pojo.lor.staticdata.StaticLoRCard`

**Comment by stelar7** [comment]
Oh yea, youre right. fixed in 2.1.21
