### ISSUE TITLE
Problem retrieving the "ඞ " summoner

### ISSUE THREAD

**Issue by KaluNight** [stelar7/R4J#51]
Hello,

I have a user who is having problems adding his account via the API. His summoner name: "ඞ ".

I can only find his account on League of Graph here: https://www.leagueofgraphs.com/summoner/euw/%E0%B6%9E%C2%A0
His OP.GG seems to be buggy.

I tried to make the requests by hand via https://developer.riotgames.com/apis#summoner-v4/GET_getBySummonerName but I can't find the account.

Do you have any idea how to solve the problem?

Thanks in advance!

**Comment by stelar7** [comment]
Hi.

This is an issue with the Riot API. It doesnt support looking up some funky names.
Feel free to create an issue here: https://github.com/RiotGames/developer-relations/issues
