### ISSUE TITLE
Summoner Endpoints get cached for a year

### ISSUE THREAD

**Issue by NichtFilip** [stelar7/R4J#55]
The Endpoints V4_SUMMONER_BY_NAME, V4_SUMMONER_BY_PUUID, V4_SUMMONER_BY_ACCOUNT, V4_SUMMONER_BY_ID get cached for a year by default. I think that's a bit too long as player level and profile icon will realistically never update.

**Comment by stelar7** [comment]
You have the option of overriding the default duration. So a year base is fine imo. #wontfix
