### ISSUE TITLE
Season is missing the type "9c91a445-4f78-1baa-a3ea-8f8aadf4914d"

### ISSUE THREAD

**Issue by spaykit** [stelar7/R4J#56]
Hey,

The enum no.stelar7.api.r4j.basic.constants.types.val.Season is missing the type "9c91a445-4f78-1baa-a3ea-8f8aadf4914d"!
Please make sure you have the latest version of the library!

**Comment by stelar7** [comment]
Thanks for the report. this is fixed in 2.2.7
