### ISSUE TITLE
Add Emerald tier type for League

### ISSUE THREAD

**Issue by BlossomiShymae** [stelar7/R4J#68]
https://www.leagueoflegends.com/en-us/news/game-updates/what-s-next-for-ranked/

The new ranked tier is likely to be added in `league-v4` after July 17-ish when Split 2 starts. :D

**Comment by spaykit** [comment]
@stelar7 can we push this today? I can create a PR.

**Comment by stelar7** [comment]
Should be fixed by https://github.com/stelar7/R4J/commit/7cbbed1a1c5738d16997690079b7119fcd80657c

**Comment by spaykit** [comment]
Thank you!
