### ISSUE TITLE
Support Spectators on the Tournament Codes. 

### ISSUE THREAD

**Issue by Dallin-Cawley** [stelar7/R4J#70]
Currently, the most summoner id's supported by the Tournament API is the sum of the two teams. If the team size is 5, the most that can be added is 10. If Spectators would like to join they'd need to be invited. It would be super helpful if the max number of summoners to a given match code would be `(teamSize * 2)+ 4` as up to 4 spectators can be added to the lobby.

**Comment by stelar7** [comment]
I assume this is fixed by #71 ?

**Comment by Dallin-Cawley** [comment]
Yes it is. Thank you.
