### ISSUE TITLE
GameModeType "CHERRY" does not exist

### ISSUE THREAD

**Issue by LaraZeyner** [stelar7/R4J#75]
Im getting the following exception:
"Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "Riot Analyser"
no.stelar7.api.r4j.basic.exceptions.APIEnumNotUpToDateException: The enum no.stelar7.api.r4j.basic.constants.types.lol.GameModeType is missing the type "CHERRY"!
Please make sure you have the latest version of the library!
If you do, send this message to the maintainer of the API."

Can you please add support for this game mode?

**Comment by stelar7** [comment]
Fixed in 2.2.19

**Comment by LaraZeyner** [comment]
Thanks
