### ISSUE TITLE
Support for queue type 490

### ISSUE THREAD

**Issue by Xahrie** [stelar7/R4J#83]
Im currently using the version 2.2.22. Im getting exceptions because the queue type 490 seems to be new/not added yet to the api. Can you resolve this issue? If this is already implemented. Which version supports it?

The enum no.stelar7.api.r4j.basic.constants.types.lol.GameQueueType is missing the type 490.0!
Please make sure you have the latest version of the library!
If you do, send this message to the maintainer of the API.

**Comment by stelar7** [comment]
Hi, this was added in 2.3.1

**Comment by Xahrie** [comment]
The last version i can find is 2.2.22. Is it now released yet?

**Comment by stelar7** [comment]
https://github.com/stelar7/R4J/releases/tag/2.3.1
