### ISSUE TITLE
Choosing what to cache

### ISSUE THREAD

**Issue by Yonygreen** [stelar7/R4J#90]
Is there a way to choose what is getting cached? Or an easy way through r4j to clear the cache?
Our server is getting filled with cached matches and timelines that we save to our database anyway. It generated over 30GB of cache data on our server

**Comment by stelar7** [comment]
You can disable the builtin cache with `DataCall.setCacheProvider(EmptyCacheProvider.INSTANCE);`

Cached items have a lifetime and are considered invalid after that time. (See [CacheLifetimeHint](https://github.com/stelar7/R4J/blob/master/src/main/java/no/stelar7/api/r4j/basic/cache/CacheLifetimeHint.java))

They will be refreshed, but there is currently nothing that deletes outdated items.
There is an open issue about this https://github.com/stelar7/R4J/issues/61
